# Generated by Django 5.2.6 on 2025-11-18 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название категории')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': '01. Категория',
                'verbose_name_plural': '01. Категории',
                'db_table': 'product_categories',
            },
        ),
        migrations.CreateModel(
            name='ProductDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(blank=True, max_length=255, null=True, verbose_name='Цвет')),
                ('storage', models.CharField(blank=True, max_length=255, null=True, verbose_name='Память')),
                ('sim', models.CharField(blank=True, max_length=255, null=True, verbose_name='SIM-карта')),
                ('battery_capacity', models.CharField(blank=True, max_length=255, null=True, verbose_name='Емкость аккумулятора')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': '05. Детали продукта',
                'verbose_name_plural': '05. Детали продукта',
                'db_table': 'product_product_details',
            },
        ),
        migrations.CreateModel(
            name='ProductProperties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название свойства')),
                ('property_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='Тип свойства')),
                ('grist_property_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='ID свойства в ГРИСТ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': '06. Свойства продукта',
                'verbose_name_plural': '06. Свойства продукта',
                'db_table': 'product_product_properties',
            },
        ),
        migrations.CreateModel(
            name='ProductRiskCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название оценки авансового платежа')),
                ('risk_category', models.CharField(blank=True, max_length=255, null=True, verbose_name='Рисковая категория')),
                ('percentage', models.FloatField(blank=True, null=True, verbose_name='Процент')),
                ('grist_product_category_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='ID категории в ГРИСТ')),
                ('grist_risk_category_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='ID рисковой категории в ГРИСТ')),
                ('grist_price_category_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='ID цены категории в ГРИСТ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': '02.  Оценка авансового платежа',
                'verbose_name_plural': '02. Оценка авансового платежа',
                'db_table': 'product_risk_categories',
            },
        ),
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Изображение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('product_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='product.productdetails', verbose_name='Детали продукта')),
            ],
            options={
                'verbose_name': '04. Изображение детали продукта',
                'verbose_name_plural': '04. Изображения детали продукта',
                'db_table': 'product_product_images',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название продукта')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена')),
                ('actual', models.BooleanField(default=True, verbose_name='Актуальный')),
                ('grist_product_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='ID продукта в ГРИСТ')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Изображение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product.categories', verbose_name='Категория')),
            ],
            options={
                'verbose_name': '03. Продукт',
                'verbose_name_plural': '03. Продукты',
                'db_table': 'product_products',
            },
        ),
        migrations.CreateModel(
            name='ProductIDs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variation_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название вариации')),
                ('variation_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='ID вариации')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ids', to='product.products', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': '09. Вариация продукта',
                'verbose_name_plural': '09. Вариации продукта',
                'db_table': 'product_product_ids',
            },
        ),
        migrations.AddField(
            model_name='productdetails',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='product.products', verbose_name='Продукт'),
        ),
        migrations.CreateModel(
            name='ProductCharacteristics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_name', models.TextField(blank=True, null=True, verbose_name='Значение свойства')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characteristics', to='product.productproperties', verbose_name='Свойство')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characteristics', to='product.products', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': '07. Характеристика продукта',
                'verbose_name_plural': '07. Характеристики продукта',
                'db_table': 'product_product_characteristics',
            },
        ),
        migrations.AlterUniqueTogether(
            name='productdetails',
            unique_together={('product', 'color', 'storage', 'sim')},
        ),
    ]
