# Generated by Django 5.2.6 on 2025-11-18 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='grist_product_id',
        ),
        migrations.AddField(
            model_name='productids',
            name='grist_product_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID продукта в ГРИСТ'),
        ),
    ]
