# Generated by Django 5.2.6 on 2025-11-19 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_remove_products_grist_product_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcharacteristics',
            name='product_ids',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='characteristics', to='product.productids', verbose_name='Вариация продукта'),
        ),
    ]
