# Generated by Django 5.2.6 on 2025-11-19 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_productcharacteristics_product_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='price_category',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Категория цены'),
        ),
    ]
