# Generated by Django 5.2.6 on 2025-11-20 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_products_price_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAutomaticallyImportedTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.IntegerField(blank=True, null=True, verbose_name='Время автоматического импорта')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': '08. Время автоматического импорта',
                'verbose_name_plural': '08. Время автоматического импорта',
                'db_table': 'product_product_automatically_imported_time',
            },
        ),
    ]
