# Generated by Django 5.2.6 on 2025-11-21 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_productautomaticallyimportedtime'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название баннера')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание баннера')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Ссылка на баннер')),
                ('image', models.ImageField(blank=True, null=True, upload_to='banners/', verbose_name='Изображение')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': '04. Баннер',
                'verbose_name_plural': '04. Баннеры',
            },
        ),
        migrations.AlterModelOptions(
            name='productautomaticallyimportedtime',
            options={'verbose_name': '03. Время автоматического импорта', 'verbose_name_plural': '03. Время автоматического импорта'},
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name': '02. Продукт', 'verbose_name_plural': '02. Продукты'},
        ),
        migrations.AddField(
            model_name='productautomaticallyimportedtime',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AddField(
            model_name='productautomaticallyimportedtime',
            name='time_type',
            field=models.CharField(choices=[('minutes', 'Минуты'), ('hours', 'Часы')], default='minutes', max_length=10, verbose_name='Тип времени'),
        ),
    ]
