# Generated by Django 5.2.6 on 2025-12-03 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_banner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productids',
            name='is_actual',
            field=models.BooleanField(default=False, verbose_name='Актуальный (из ГРИСТ)'),
        ),
        migrations.AddField(
            model_name='products',
            name='is_actual',
            field=models.BooleanField(default=False, verbose_name='Актуальный (из ГРИСТ)'),
        ),
    ]
