# Generated by Django 5.2.7 on 2025-10-31 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Variations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название вариации')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': '02. Вариация',
                'verbose_name_plural': '02. Вариации',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название продукта')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена')),
                ('battery_capacity', models.CharField(blank=True, max_length=255, null=True, verbose_name='Емкость аккумулятора')),
                ('actual', models.BooleanField(default=True, verbose_name='Актуальный')),
                ('processor', models.CharField(blank=True, max_length=255, null=True, verbose_name='Процессор')),
                ('screen_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название экрана')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.categories', verbose_name='Категория')),
                ('variation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.variations', verbose_name='Вариация')),
            ],
            options={
                'verbose_name': '03. Продукт',
                'verbose_name_plural': '03. Продукты',
            },
        ),
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Изображение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.products', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': '04. Изображение продукта',
                'verbose_name_plural': '04. Изображения продукта',
            },
        ),
        migrations.CreateModel(
            name='ProductColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(blank=True, max_length=255, null=True, verbose_name='Цвет')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colors', to='products.products', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': '05. Цвет продукта',
                'verbose_name_plural': '05. Цвета продукта',
            },
        ),
        migrations.CreateModel(
            name='ProductCamera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera', models.CharField(blank=True, max_length=255, null=True, verbose_name='Камера')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cameras', to='products.products', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': '07. Камера продукта',
                'verbose_name_plural': '07. Камеры продукта',
            },
        ),
        migrations.CreateModel(
            name='ProductStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage', models.CharField(blank=True, max_length=255, null=True, verbose_name='Память')),
                ('quantity', models.IntegerField(blank=True, null=True, verbose_name='Количество')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storages', to='products.products', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': '06. Память продукта',
                'verbose_name_plural': '06. Память продукта',
            },
        ),
    ]
