# Generated by Django 5.2.7 on 2025-10-31 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_variations_products_productimages_productcolor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSimCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sim_card', models.CharField(blank=True, max_length=255, null=True, verbose_name='SIM-карта')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sim_cards', to='products.products', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': '08. SIM-карта продукта',
                'verbose_name_plural': '08. SIM-карты продукта',
            },
        ),
    ]
