# Generated by Django 5.2.7 on 2025-10-31 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productsimcard'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductIDs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grist_product_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='ID продукта в ГРИСТ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ids', to='products.products', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': '09. ID продукта в ГРИСТ',
                'verbose_name_plural': '09. ID продукта в ГРИСТ',
            },
        ),
    ]
