# Generated by Django 5.2.7 on 2025-10-31 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_productids'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcolor',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productsimcard',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productstorage',
            name='product',
        ),
        migrations.CreateModel(
            name='ProductDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(blank=True, max_length=255, null=True, verbose_name='Цвет')),
                ('storage', models.CharField(blank=True, max_length=255, null=True, verbose_name='Память')),
                ('camera', models.CharField(blank=True, max_length=255, null=True, verbose_name='Камера')),
                ('sim_card', models.CharField(blank=True, max_length=255, null=True, verbose_name='SIM-карта')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='products.products', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': '05. Детали продукта',
                'verbose_name_plural': '05. Детали продукта',
            },
        ),
        migrations.DeleteModel(
            name='ProductCamera',
        ),
        migrations.DeleteModel(
            name='ProductColor',
        ),
        migrations.DeleteModel(
            name='ProductSimCard',
        ),
        migrations.DeleteModel(
            name='ProductStorage',
        ),
    ]
