# Generated by Django 5.2.7 on 2025-10-31 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_duplicate_productdetails'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productids',
            options={'verbose_name': '09. Вариация продукта', 'verbose_name_plural': '09. Вариации продукта'},
        ),
        migrations.RemoveField(
            model_name='productids',
            name='grist_product_id',
        ),
        migrations.AddField(
            model_name='productids',
            name='variation_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название вариации'),
        ),
        migrations.AlterUniqueTogether(
            name='productdetails',
            unique_together={('product', 'color', 'storage', 'sim_card')},
        ),
    ]
