# Generated by Django 5.2.6 on 2025-11-01 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_productids_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='variation',
        ),
        migrations.DeleteModel(
            name='Variations',
        ),
    ]
