# Generated by Django 5.2.7 on 2025-11-01 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_remove_products_variation_delete_variations'),
    ]

    operations = [
        migrations.AddField(
            model_name='productids',
            name='variation_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID вариации'),
        ),
    ]
