# Generated by Django 5.2.6 on 2025-11-01 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_productids_variation_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdetails',
            name='camera',
        ),
    ]
