# Generated by Django 5.2.7 on 2025-11-01 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_remove_camera_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductProperties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название свойства')),
                ('value', models.CharField(blank=True, max_length=255, null=True, verbose_name='Значение свойства')),
                ('grist_property_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='ID свойства в ГРИСТ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': '06. Свойства продукта',
                'verbose_name_plural': '06. Свойства продукта',
            },
        ),
        migrations.CreateModel(
            name='ProductCharacteristics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characteristics', to='products.products', verbose_name='Продукт')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characteristics', to='products.productproperties', verbose_name='Свойство')),
            ],
            options={
                'verbose_name': '07. Характеристики продукта',
                'verbose_name_plural': '07. Характеристики продукта',
                'unique_together': {('product', 'property')},
            },
        ),
    ]
