# Generated by Django 5.2.7 on 2025-11-02 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_productproperties_productcharacteristics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productproperties',
            name='value',
        ),
        migrations.AddField(
            model_name='productcharacteristics',
            name='value',
            field=models.TextField(blank=True, null=True, verbose_name='Значение свойства'),
        ),
        migrations.AddField(
            model_name='productproperties',
            name='type',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Тип свойства'),
        ),
    ]
