# Generated by Django 5.2.7 on 2025-11-02 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_remove_productproperties_value_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productcharacteristics',
            unique_together=set(),
        ),
    ]
