# Generated by Django 5.2.7 on 2025-11-02 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_alter_productcharacteristics_unique_together'),
    ]

    operations = [
    ]
