# Generated by Django 5.2.6 on 2025-11-03 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_remove_unique_together_productcharacteristics'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название категории')),
                ('risk_category', models.CharField(blank=True, max_length=255, null=True, verbose_name='Рисковая категория')),
                ('percentage', models.FloatField(blank=True, null=True, verbose_name='Процент')),
                ('grist_product_category_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='ID категории в ГРИСТ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': '02. Категория продукта',
                'verbose_name_plural': '02. Категории продукта',
            },
        ),
        migrations.AddField(
            model_name='products',
            name='product_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.productcategory', verbose_name='Категория продукта'),
        ),
    ]
