# Generated by Django 5.2.7 on 2025-11-03 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_productcategory_products_product_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcategory',
            options={'verbose_name': '02.  Оценка авансового платежа', 'verbose_name_plural': '02. Оценка авансового платежа'},
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название оценки авансового платежа'),
        ),
    ]
