# Generated by Django 5.2.7 on 2025-11-03 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_alter_productcategory_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='product_category',
        ),
    ]
