# Generated by Django 5.2.7 on 2025-11-03 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_remove_products_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='grist_product_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID продукта в ГРИСТ'),
        ),
    ]
