# Generated by Django 5.2.7 on 2025-11-03 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_products_grist_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='grist_price_category_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID цены категории в ГРИСТ'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='grist_risk_category_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID рисковой категории в ГРИСТ'),
        ),
    ]
