# Generated by Django 5.2.7 on 2025-11-10 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_productcategory_grist_price_category_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название баннера')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание баннера')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Ссылка на баннер')),
                ('image', models.ImageField(blank=True, null=True, upload_to='banners/', verbose_name='Изображение')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': '08. Баннер',
                'verbose_name_plural': '08. Баннеры',
            },
        ),
    ]
