# Generated by Django 5.2.7 on 2025-10-31 04:46

import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phone_number', models.CharField(blank=True, help_text='Необязательно. Введите ваш номер телефона.', max_length=15, null=True, unique=True, verbose_name='Номер телефона')),
                ('date_of_birth', models.DateField(blank=True, help_text='Необязательно. Введите вашу дату рождения.', null=True, verbose_name='Дата рождения')),
                ('avatar', models.ImageField(blank=True, help_text='Необязательно. Загрузите ваше фото профиля.', null=True, upload_to='avatars/', verbose_name='Аватар')),
                ('address', models.TextField(blank=True, help_text='Необязательно. Введите ваш адрес.', null=True, verbose_name='Адрес')),
                ('city', models.CharField(blank=True, help_text='Необязательно. Введите ваш город.', max_length=255, null=True, verbose_name='Город')),
                ('street', models.CharField(blank=True, help_text='Необязательно. Введите вашу улицу.', max_length=255, null=True, verbose_name='Улица')),
                ('house', models.CharField(blank=True, help_text='Необязательно. Введите номер дома.', max_length=50, null=True, verbose_name='Дом')),
                ('apartment', models.CharField(blank=True, help_text='Необязательно. Введите номер квартиры.', max_length=50, null=True, verbose_name='Квартира')),
                ('postal_index', models.CharField(blank=True, help_text='Необязательно. Введите почтовый индекс.', max_length=20, null=True, verbose_name='Индекс')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('reset_token', models.CharField(blank=True, help_text='Токен для сброса пароля', max_length=100, null=True, verbose_name='Токен сброса пароля')),
                ('reset_token_expires', models.DateTimeField(blank=True, null=True, verbose_name='Время истечения токена')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '01. Пользователь',
                'verbose_name_plural': '01. Пользователи',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SmsCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6, verbose_name='Код')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('expires_at', models.DateTimeField(verbose_name='Дата истечения')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '02. SMS код',
                'verbose_name_plural': '02. SMS коды',
                'ordering': ['-created_at'],
            },
        ),
    ]
