# Generated by Django 5.2.7 on 2025-11-01 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EskizToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField(verbose_name='Token')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('expires_at', models.DateTimeField(verbose_name='Дата истечения')),
            ],
            options={
                'verbose_name': '03. Eskiz Token',
                'verbose_name_plural': '03. Eskiz Tokens',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='smscode',
            name='is_used',
            field=models.BooleanField(default=False, verbose_name='Использован'),
        ),
    ]
