# Generated by Django 5.2.6 on 2025-11-20 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_eskiztoken_smscode_is_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='pnfl',
            field=models.CharField(blank=True, help_text='Необязательно. Введите ваш PNFL.', max_length=14, null=True, verbose_name='PNFL'),
        ),
    ]
