# Generated by Django 5.2.6 on 2025-11-20 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_pnfl'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_veriifed_my_id',
            field=models.BooleanField(default=False, help_text='Необязательно. Введите ваш мой ID.', verbose_name='Подтвержден ли мой ID'),
        ),
    ]
