# Generated by Django 5.2.6 on 2025-11-20 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_is_veriifed_my_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='country',
            field=models.CharField(blank=True, help_text='Необязательно. Введите вашу страну.', max_length=255, null=True, verbose_name='Страна'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='region',
            field=models.CharField(blank=True, help_text='Необязательно. Введите ваш регион.', max_length=255, null=True, verbose_name='Регион'),
        ),
    ]
