# Generated by Django 5.2.6 on 2025-12-06 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customuser_country_customuser_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='pass_data',
            field=models.CharField(blank=True, help_text='Необязательно. Введите вашу серию и номер паспорта.', max_length=9, null=True, verbose_name='Серия и номер паспорта'),
        ),
    ]
