# Generated by Django 5.2.6 on 2025-12-20 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_customuser_pass_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='citizenship',
            field=models.CharField(blank=True, help_text='Необязательно. Гражданство пользователя.', max_length=255, null=True, verbose_name='Гражданство'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='nationality',
            field=models.CharField(blank=True, help_text='Необязательно. Национальность пользователя.', max_length=255, null=True, verbose_name='Национальность'),
        ),
    ]
