# Generated by Django 5.2.7 on 2025-11-02 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tariffs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название тарифа')),
                ('payments_count', models.IntegerField(blank=True, null=True, verbose_name='Количество платежей')),
                ('offset_days', models.IntegerField(blank=True, null=True, verbose_name='Количество дней отсрочки')),
                ('type', models.CharField(blank=True, max_length=255, null=True, verbose_name='Тип тарифа')),
                ('grist_tariff_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='ID тарифа в ГРИСТ')),
                ('coefficient', models.FloatField(blank=True, null=True, verbose_name='Коэффициент')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': '01. Тарифы',
                'verbose_name_plural': '01. Тарифы',
            },
        ),
    ]
