# Generated by Django 5.2.6 on 2025-11-03 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_ordercaluculationmode_orders_orderitems'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitems',
            name='down_payment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Первоначальный взнос'),
        ),
        migrations.AlterField(
            model_name='orderitems',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='order.orders', verbose_name='Заказ'),
        ),
        migrations.CreateModel(
            name='OrderPaymentSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_number', models.IntegerField(verbose_name='Номер месяца')),
                ('payment_date', models.DateField(verbose_name='Дата платежа')),
                ('monthly_payment_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма ежемесячного платежа')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Оплачено')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата оплаты')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_schedule', to='order.orderitems', verbose_name='Товар заказа')),
            ],
            options={
                'verbose_name': '04. График платежей',
                'verbose_name_plural': '04. График платежей',
                'ordering': ['order_item', 'month_number'],
            },
        ),
    ]
