# Generated by Django 5.2.7 on 2025-11-03 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_orderitems_down_payment_alter_orderitems_order_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название компании')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес компании')),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True, verbose_name='Широта')),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True, verbose_name='Долгота')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': '03. Адреса компаний',
                'verbose_name_plural': '03. Адреса компаний',
            },
        ),
        migrations.AddField(
            model_name='orders',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес доставки'),
        ),
        migrations.AddField(
            model_name='orders',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True, verbose_name='Широта'),
        ),
        migrations.AddField(
            model_name='orders',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True, verbose_name='Долгота'),
        ),
        migrations.AddField(
            model_name='orders',
            name='company_address',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='order.companyaddress', verbose_name='Адрес компании'),
            preserve_default=False,
        ),
    ]
