# Generated by Django 5.2.6 on 2025-11-03 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_companyaddress_orders_address_orders_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='company_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.companyaddress', verbose_name='Адрес компании'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True, verbose_name='Долгота'),
        ),
    ]
