# Generated by Django 5.2.6 on 2025-11-21 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_alter_orders_status'),
        ('product', '0006_banner_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyaddress',
            options={'verbose_name': '02. Адреса компаний', 'verbose_name_plural': '02. Адреса компаний'},
        ),
        migrations.AlterModelOptions(
            name='orderitems',
            options={'verbose_name': '04. Товары заказа', 'verbose_name_plural': '04. Товары заказа'},
        ),
        migrations.AlterModelOptions(
            name='orders',
            options={'verbose_name': '03. Заказы', 'verbose_name_plural': '03. Заказы'},
        ),
        migrations.AddField(
            model_name='orderitems',
            name='variation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product.productids', verbose_name='Вариация'),
            preserve_default=False,
        ),
    ]
