# Generated by Django 5.2.6 on 2025-11-21 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_alter_companyaddress_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_calculation_mode',
            field=models.CharField(choices=[('mode_1', 'Режим 1: Общий первоначальный взнос'), ('mode_2', 'Режим 2: Индивидуальный первоначальный взнос')], max_length=255, verbose_name='Режим расчета'),
        ),
        migrations.DeleteModel(
            name='OrderCaluculationMode',
        ),
    ]
