# Generated by Django 5.2.6 on 2025-11-21 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_alter_orders_order_calculation_mode_and_more'),
        ('product', '0006_banner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitems',
            name='variation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.productids', verbose_name='Вариация'),
        ),
    ]
