# Generated by Django 5.2.6 on 2025-11-25 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_alter_orderitems_variation'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='counterparty_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID контрагента'),
        ),
    ]
