# Generated by Django 5.2.6 on 2025-12-05 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_orders_counterparty_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tariffs',
            name='for_mobile_app',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Для мобильного приложения'),
        ),
    ]
