# Generated by Django 5.2.6 on 2025-12-06 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_tariffs_for_mobile_app'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('preparing', 'Заказ готовится'), ('ready', 'Заказ готов'), ('delivering', 'Доставляется'), ('finished', 'Заказ получен')], default='preparing', max_length=255, verbose_name='Статус заказа'),
        ),
    ]
